routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
})->name('home');
Route::group(['prefix' => '/admin/', 'namespace' => 'Admin',
    'middleware' => ['auth', 'role:Admin|Operator']
], function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard.index');
    })->name('dashboard');

    Route::group(['prefix' => '/access/', 'namespace' => 'Access'], function () {
        Route::resources([
            'user' => 'UserController',
            'role' => 'RoleController'
        ]);
    });


    Route::resources([
        'bus' => 'BusController',
        'bus-type' => 'BusTypeController',
        'route' => 'RouteController',
        'city' => 'CityController',
        'gallery' => 'GalleryController',
        'amenities' => 'AmenitiesController',
        'seat-arrangement' => 'SeatArrangementController',
        'booking' => 'BookingController',
        'operator' => 'OperatorController'
    ]);
    Route::get('all-shifts', "BusController@getAllShifts")->name('route-list');
    Route::get('route-list', "BusController@routeList")->name('route-list');
    Route::get('bus_type', "BusController@busType")->name('bus_type');
    Route::get('seat-arrangement/{id}/duplicate', "SeatArrangementController@duplicate")->name('seat-arrangement.duplicate');
    Route::get('seat-arrangement/assign/{id}', "SeatArrangementController@assign");
    Route::post('seat-arrangement/assign', "SeatArrangementController@postAssign")->name('seat-arrangement.assign');
    Route::get('bus-type/toggle/{id}', "BusTypeController@toggleStatus")->name('bus-type.toggle');
    Route::get('stop-delete', "BusController@stopDelete")->name('stop-delete');
    Route::get('amenities/toggle/{id}', "AmenitiesController@toggleStatus")->name('amenities.toggle');
    Route::get('bus/toggle/{id}', "BusController@toggleStatus")->name('bus.toggle');
    Route::get('bus/toggle-approval/{id}', "BusController@toggleApproval")->name('bus.toggle-approval');
    Route::get('operators/toggle/{id}', "OperatorController@toggleStatus")->name('operators.toggle');
    Route::get('operators/toggleapproval/{id}', "OperatorController@toggleApproval")->name('operators.toggleapproval');
    Route::get('city/toggle/{id}', "CityController@toggleStatus")->name('city.toggle');
    Route::get('route/toggle/{id}', "RouteController@toggleStatus")->name('route.toggle');

});
Route::get('partner', "PagesController@partner")->name('partner-home');

Route::get('operator/register', "Auth\OperatorRegisterController@showRegistrationForm")->name('auth.operator.register');
Route::post('operator/register', "Auth\OperatorRegisterController@register");

//Route::get('/', 'HomeController@index')->name('home');
//Route::get('/search', 'SearchController@index')->name('search.index');
Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Config;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class, Config::get('entrust::assigned_roles_table'));
    }

    public function deferAndAttachNewRole($role)
    {
        // remove any roles tagged in this user.
        foreach ($this->roles as $userRole) {
            $this->roles()->detach($userRole->id);
        }

        // attach the new role using the `EntrustUserTrait` `attachRole()`
        $this->attachRole($role);
    }
    public function operator()
    {
        return $this->hasOne(Operator::class);
    }
}

app/Http/Controllers/Admin/Access/RoleController.php
<?php

namespace App\Http\Controllers\Admin\Access;

use App\Permission;
use App\Resource;
use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('admin.access._role.index')->with('roles',Role::with('perms')->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.access._role.create')->with('permissions',Permission::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
       $role= Role::create([
           'name'=>$request->name,
           'display_name'=>$request->display_name,
           'description'=>$request->description,

        ]);
       if($request->permissions){
           foreach ($request->permissions as $key=>$value){
               $role->attachPermission($value);
           }
       }

        return  redirect()->route('role.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $role=Role::where('id',$id)->first();
        return view('admin.access._role.edit')->with('role',$role);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/Access/UserController.php
<?php

namespace App\Http\Controllers\Admin\Access;

use App\Http\Controllers\Backend\Access\RoleController;
use App\Role;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */

    public function index()
    {
        return view('admin.access._user.index')->with('users', User::with('roles')->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        //
        return view('admin.access._user.create')
            ->with('roles', Role::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function store(Request $request)
    {
        //
        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password),


        ]);
//        $user->attachRole($request->roles);

        foreach ($request->roles as $key => $value) {
            $user->attachRole($value);
        }


        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $user = User::where('id', $id)->with('roles')->first();

        return view('admin.access._user.edit')->with('user', $user)->withRoles(Role::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, $id)
    {
         User::where('id', $id)->update([
            'name' => $request->name,
            'email' => $request->email,

        ]);
         $user=User::where('id',$id)->first();
//        $user->detachRole($user);

//        dd($request->roles);
        $user->roles()->sync($request->roles );

//        foreach ($request->roles as $key => $value) {
//            $user->deferAndAttachNewRole($value);
//            $user->attachRole($value);
//        }
//        Session::flash('message', 'Successfully updated category!');
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/access/_user/create.blade.php
@extends('admin.layout.master')
@section('content')
    <section class="content-header">
        <h1>
            User Management
            <small>create user</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Access</li>
            <li class="active">User Management</li>
            <li class="active">Create user</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="panel">
            <div class="panel-heading">
                <h3>Create User</h3>

            </div>
            <div class="panel-body">
                <form class="form-horizontal" role="form" method="POST" action="{{route('user.store')}}">
                    <div class="form-group row">

                        <label for="name" class="control-label col-lg-2">Name</label>


                        <div class="col-lg-10">

                            <input type="text" class="form-control" name="name" placeholder="Full Name"
                                   required/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name" class="control-label col-lg-2">Email</label>
                        <div class="col-lg-10">
                            <input type="email" class="form-control" name="email" placeholder="Email" required/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name" class="control-label col-lg-2">Password</label>
                        <div class="col-lg-10">
                            <input type="password" class="form-control" name="password" placeholder="Password" required/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name" class="control-label col-lg-2">Confirm Password</label>
                        <div class="col-lg-10">
                            <input type="password" class="form-control" name="confirm password" placeholder="Confirm Password"
                                   required/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name" class="control-label col-lg-2">Associated role</label>
                        <div class="col-lg-10">
                            @foreach($roles as $role)
                                <input type="checkbox" name="roles[]"  value="{{$role->id}}"/>
                                <label>{{$role->name}}</label>
                                <br>
                            @endforeach

                        </div>
                    </div>
                    {{csrf_field()}}
                    <button type="submit" class="btn btn-success pull-right">Create</button>
                </form>

            </div>
        </div>


    </section><!-- /.content -->
@endsection

resources/views/admin/access/_user/edit.blade.php
<div class="modal-header">
    <span class="modal-title" >Edit User</span>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form class="form-horizontal edit-user-form" method="POST" action="{{route('user.update',$user)}} ">

        <div class="row form-group">
            <div class="col-sm-3"><label class="control-label">Full Name</label></div>
            <div class="col-sm-9">
                <input type="text" class="form-control" placeholder="Enter role name" id="name"
                       name="name" value="{{$user->name}}" required/>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-3"><label class="control-label">Email</label></div>
            <div class="col-sm-9">
                <input type="email" class="form-control" placeholder="Enter role name" id="email"
                       name="email" value="{{$user->email}}"  required/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-3"><label class="control-label">Associated Roles:</label></div>

            <div class="col-sm-9">

                @foreach($roles as $role)
                    <input type="checkbox" name="roles[]" @if($user->roles->contains($role)) checked @endif  value="{{$role->id}}"/>
                    <label>{{$role->name}}</label>
                    <br>
                @endforeach

            </div>
        </div>
        {{ method_field('PATCH') }}
        {{csrf_field()}}
    </form>

</div>
<div class="modal-footer">
    {{--<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>--}}
    <button type="button" id="edit-user-submit" class="btn btn-success save-course-btn">Save changes</button>
</div>

<script>
    $(document).ready(function(){
        $('#edit-user-submit').click(function(){
            $('.edit-user-form').submit();
        });
    });
</script>

resources/views/admin/access/_user/index.blade.php
@extends('admin.layout.master')
@section('content')
    <section class="content-header">
        <h1>
            User Management
            <small>Active Users</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Access</li>
            <li class="active">User Management</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="panel">
            <div class="panel-heading">
                {{--<h3>all active users</h3>--}}
                <a href="{{route('user.create')}}" class="btn btn-success">create user</a>

                <span class="pull-right">
                    {{--<a href="user.create" class="btn btn-success">create user</a>--}}
                    {{--<a href="#" class="btn btn-success">create user</a>--}}
                    <input class="form-control" type="text" placeholder="search"/>
                </span>

            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Created At</th>
                            <th>Updated At</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td>{{$user->id}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>

                                <td>
                                    @foreach($user->roles as $role)
                                        {{$role->name}}
                                    @endforeach
                                </td>
                                <td>{{$user->created_at}}</td>
                                <td>{{$user->updated_at}}</td>
                                <td>
                                    <i data-id="{{$user->id}}" class="btn fa fa-pencil bg-blue edit"></i>

                                    <i class="btn fa fa-times bg-aqua"></i>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>

                    </table>

                </div>

            </div>
        </div>

        <!-- Edit User Modal -->
        <div class="modal " id="edit-user" tabindex="-1" role="dialog" aria-labelledby="edit-userLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">

                </div>
            </div>
        </div>
    </section><!-- /.content -->
    <script>

        $(document).ready(function (e) {


            $('body').on("click", '.edit', function (e) {
                let user_id = $(this).data('id');
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                e.preventDefault();


                $.ajax({

                    url: 'user/' + user_id + '/edit',

                    success: function (response) {

                        $('#edit-user .modal-content').html(response);
                        $('#edit-user').modal('toggle');

                    }

                });
            });

        });

    </script>

@endsection