routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
})->name('home');
Route::group(['prefix' => '/admin/', 'namespace' => 'Admin',
    'middleware' => ['auth', 'role:Admin|Operator']
], function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard.index');
    })->name('dashboard');

    Route::group(['prefix' => '/access/', 'namespace' => 'Access'], function () {
        Route::resources([
            'user' => 'UserController',
            'role' => 'RoleController'
        ]);
    });


    Route::resources([
        'bus' => 'BusController',
        'bus-type' => 'BusTypeController',
        'route' => 'RouteController',
        'city' => 'CityController',
        'gallery' => 'GalleryController',
        'amenities' => 'AmenitiesController',
        'seat-arrangement' => 'SeatArrangementController',
        'booking' => 'BookingController',
        'operator' => 'OperatorController'
    ]);
    Route::get('all-shifts', "BusController@getAllShifts")->name('route-list');
    Route::get('route-list', "BusController@routeList")->name('route-list');
    Route::get('bus_type', "BusController@busType")->name('bus_type');
    Route::get('seat-arrangement/{id}/duplicate', "SeatArrangementController@duplicate")->name('seat-arrangement.duplicate');
    Route::get('seat-arrangement/assign/{id}', "SeatArrangementController@assign");
    Route::post('seat-arrangement/assign', "SeatArrangementController@postAssign")->name('seat-arrangement.assign');
    Route::get('bus-type/toggle/{id}', "BusTypeController@toggleStatus")->name('bus-type.toggle');
    Route::get('stop-delete', "BusController@stopDelete")->name('stop-delete');
    Route::get('amenities/toggle/{id}', "AmenitiesController@toggleStatus")->name('amenities.toggle');
    Route::get('bus/toggle/{id}', "BusController@toggleStatus")->name('bus.toggle');
    Route::get('bus/toggle-approval/{id}', "BusController@toggleApproval")->name('bus.toggle-approval');
    Route::get('operators/toggle/{id}', "OperatorController@toggleStatus")->name('operators.toggle');
    Route::get('operators/toggleapproval/{id}', "OperatorController@toggleApproval")->name('operators.toggleapproval');
    Route::get('city/toggle/{id}', "CityController@toggleStatus")->name('city.toggle');
    Route::get('route/toggle/{id}', "RouteController@toggleStatus")->name('route.toggle');

});
Route::get('partner', "PagesController@partner")->name('partner-home');

Route::get('operator/register', "Auth\OperatorRegisterController@showRegistrationForm")->name('auth.operator.register');
Route::post('operator/register', "Auth\OperatorRegisterController@register");

//Route::get('/', 'HomeController@index')->name('home');
//Route::get('/search', 'SearchController@index')->name('search.index');
Auth::routes();

app/Bus.php
<?php

namespace App;

use App\Http\Traits\EnumTrait;
use Illuminate\Database\Eloquent\Model;

class Bus extends Model
{
    use EnumTrait;

    protected $fillable = [
        'name', 'contact_no', 'registration_number', 'route_id', 'type_id', 'operator_id', 'seat_arrangement_id'
    ];

// TODO fix migration Dec/12/2018

    public function busType()
    {
        return $this->belongsTo(BusType::class, 'type_id');
    }

    public function route()
    {
        return $this->hasOne(Route::class);
    }

    public function operator()
    {
        return $this->belongsTo(Operator::class);
    }

    public function amenities()
    {
        return $this->belongsToMany(Amenities::class, 'amenities_buses');
    }

    public function schedules()
    {
        return $this->belongsTo(Schedule::class);
    }

    public function seat_arrangement()
    {
        return $this->belongsToMany(SeatArrangement::class);
    }

    public function stops()
    {
        return $this->hasMany(Stop::class);
    }
    public function bookings()
    {
        return $this->hasMany(Booking::class);
    }

}

app/BusType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BusType extends Model
{
    protected $fillable = ['name'];
}

app/Http/Controllers/Admin/BusController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Amenities;
use App\Bus;
use App\BusType;
use App\Route;
use App\SeatArrangement;
use App\Stop;
use App\Operator;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class BusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        if (Auth::user()->hasRole('Operator')) {
            $operator_id = Operator::where('user_id', Auth::user()->id)->first()->id;
            $buses = Bus::where('operator_id', $operator_id)->get();
        } else {
            $buses = Bus::all();
        }

        return view('admin.bus.index')->with('buses', $buses);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $routes = Route::all();
        $bus_types = BusType::all();
        $amenities = Amenities::all();
        $operators = Operator::all();
        $seat_arrangements = SeatArrangement::all();
        $shifts = Bus::getPossibleEnumValues('shift');

        return view('admin.bus.create')
            ->with('bus_types', $bus_types)
            ->with('routes', $routes)
            ->with('operators', $operators)
            ->with('seat_arrangements', $seat_arrangements)
            ->with('shifts', $shifts)
            ->with('amenities', $amenities);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'type_id' => 'required',
            'registration_number' => 'required',
            'contact_no' => 'required',
        ]);

        $operator_id = $request->operator_id ?
            $request->operator_id :
            Operator::where('user_id', Auth::user()->id)->first()->id;

        $bus = Bus::create([
            'name' => $request->name,
            'contact_no' => $request->contact_no,
            'operator_id' => $operator_id,
            'registration_number' => $request->registration_number,
            'shift' => $request->shift,
            'type_id' => $request->type_id
        ]);
        $bus->amenities()->attach($request->amenities);

        Session::flash('success', 'Successfully Added!');

        return redirect()->route('bus.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->hasRole('Operator') && !Operator::hasBus($id)) {
            return redirect()->route('bus.index');
        }

        $bus = Bus::find($id);
        $bus_amenities = [];

        foreach ($bus->amenities as $bus_amenity) {
            array_push($bus_amenities, $bus_amenity->id);
        }

        if (Auth::user()->hasRole('Operator')) {
            $seat_arrangements = SeatArrangement::whereHas('operator', function ($query) {
                $query->where('operators.id', Operator::where('user_id', Auth::user()->id)->first()->id);
            })->get();
        } else {
            $seat_arrangements = SeatArrangement::all();
        }


        return view('admin.bus.edit', ['bus' => $bus,
            'amenities' => Amenities::all(),
            'routes' => Route::all(),
            'operators' => Operator::all(),
            'bus_amenities' => $bus_amenities,
            'seat_arrangements' => $seat_arrangements,
            'bus_types' => BusType::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
//        dd(array_filter($request->schedules));
        $this->validate($request, [
            'name' => 'required',
            'registration_number' => 'required'
        ]);
        $operator_id = $request->operator_id ?
            $request->operator_id :
            Operator::where('user_id', Auth::user()->id)->first()->id;

        Bus::find($id)->update([
            'name' => $request->name,
            'contact_no' => $request->contact_no,
            'operator_id' => $operator_id,
            'registration_number' => $request->registration_number,
            'type_id' => $request->type_id,
        ]);
        Bus::find($id)->amenities()->sync($request->amenities);
        Bus::find($id)->seat_arrangement()->sync($request->seat_arrangement_id);

        if ($request->stop_name) {
            foreach (array_filter($request->stop_name) as $index => $stop_name) {
                Bus::find($id)->stops()->updateOrCreate([
                    'id' => $request->stop[$index]
                ], [
                    'name' => $stop_name,
                    'description' => $request->description[$index],
                    'time' => $this->parseTime($request->time[$index]),
                    'city_id' => $request->city[$index],
                ]);
            }
        }
        Bus::find($id)->schedules()->updateOrCreate([
            'bus_id' => $request->bus_id,
            'sunday' => $request->Sunday,
            'monday' => $request->Monday,
            'tuesday' => $request->Tuesday,
            'wednesday' => $request->Wednesday,
            'thursday' => $request->Thursday,
            'friday' => $request->Friday,
            'saturday' => $request->Saturday,
        ]);


        Session::flash('success', 'Successfully updated!');

        return redirect()->route('bus.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Bus::destroy($id);
        return response('success');
    }

    public function routeList(Request $request)
    {
        $route = Route::where('id', $request->id)->first();
        $bus = Bus::find($request->bus);
        return view('admin.bus._partials.ajax_route_list')
            ->with('route', $route)
            ->with('bus', $bus);
    }

    public function parseTime($time)
    {
        return Carbon::createFromTimeStamp(strtotime($time));
    }

    public function stopDelete(Request $request)
    {
        Stop::destroy($request->id);
    }

    public function toggleStatus($id)
    {
        $buses = Bus::findOrFail($id);
        Bus::where('id', $id)->update(['status' => !$buses->status]);
        Session::flash('message', 'Successfully updated!');
        Session::flash('alert-class', 'alert-info');

        return redirect()->route('bus.index');
    }

    public function toggleApproval($id)
    {
        $bus = Bus::findOrFail($id);
        Bus::where('id', $id)->update(['approval' => !$bus->approval]);
        Session::flash('message', 'Successfully updated!');
        Session::flash('alert-class', 'alert-info');

        return redirect()->route('bus.index');
    }

    public function busType(Request $request)
    {
        if (Auth::user()->hasRole('Operator')) {
            $seat_arrangements = SeatArrangement::where('bus_type_id', $request->id)
                ->whereHas('operator', function ($query) {
                    $query->where('operators.id', Operator::where('user_id', Auth::user()->id)->first()->id);
                })
                ->get();
        } else {
            $seat_arrangements = SeatArrangement::where('bus_type_id', $request->id)->get();
        }
        return $seat_arrangements;
    }
}

resources/views/admin/bus/create.blade.php
@extends('admin.layout.master')
@section('content')
    <section class="content-header">
        <h1>
            Bus Management
            <small>Add new bus</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Bus management</li>
            <li class="active">Add new bus</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-warning">
                    <!-- left column -->
                    <div class="panel-body">
                        <form role="form" action="{{route('bus.store')}}" method="post" class="validate"
                              enctype="multipart/form-data">
                            <div class="tab-content">
                                <div class="panel-body tab-pane  active" id="bus_info">
                                    <div class="alert alert-info"><i class="fa fa-info-circle"></i> Add new Bus
                                        <p>
                                            Use the form below to start creating your bus. You need to define a route
                                            that this
                                            bus
                                            operates on and a bus type. Then you'll have to define departure and arrival
                                            time
                                            for
                                            each location (bus stop) along the selected route. After saving you will be
                                            able to
                                            define the rest of the bus settings.
                                        </p>
                                    </div>
                                    <div class="row">
                                        @if(Auth::user()->hasRole('Admin'))
                                            <div class="form-group col-md-6 ">
                                                <label>Operator</label>
                                                <select tabindex="-1"
                                                        class="form-control select2 route required select2-hidden-accessible"
                                                        style="width: 100%;" name="operator_id" aria-hidden="true">
                                                    <option></option>
                                                    @foreach($operators as $operator)
                                                        <option value="{{$operator->id}}">{{$operator->name}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        @endif
                                        <div class="form-group col-md-6 {{ $errors->has('name') ? ' has-error' : '' }}">
                                            <label for="exampleInputEmail1">Bus Name</label>
                                            <input type="text" class="form-control required" tabindex="1"
                                                   data-parsley-trigger="change" data-parsley-minlength="2"
                                                   data-parsley-maxlength="15" data-parsley-pattern="^[a-zA-Z\  \/]+$"
                                                   name="name" placeholder="Bus Name">
                                            @if ($errors->has('name'))
                                                <span class="help-block form-control-feedback ">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-6 ">
                                            <label>Bus Type</label>
                                            <select tabindex="-1"
                                                    class="form-control select2 required select2-hidden-accessible bus_type "
                                                    style="width: 100%;" name="type_id" aria-hidden="true">
                                                <option></option>
                                                @foreach($bus_types as $bus_type)
                                                    <option value="{{$bus_type->id}}">{{$bus_type->name}}</option>
                                                @endforeach
                                            </select>
                                            @if ($errors->has('type_id'))
                                                <span class="help-block form-control-feedback ">
                                                <strong>{{ $errors->first('type_id') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-6 ">
                                            <label>Shift</label>
                                            <select tabindex="-1"
                                                    class="form-control select2 required select2-hidden-accessible bus_type "
                                                    style="width: 100%;" name="shift" aria-hidden="true">
                                                <option></option>
                                                @foreach($shifts as $shift)
                                                    <option >{{$shift}}</option>
                                                @endforeach
                                            </select>
                                            @if ($errors->has('shift'))
                                                <span class="help-block form-control-feedback ">
                                                <strong>{{ $errors->first('shift') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-6 ">
                                            <label>Contact No.</label>
                                            <input tabindex="2" type="text" class="form-control required"
                                                   name="contact_no"
                                                   data-parsley-trigger="change" data-parsley-minlength="2"
                                                   data-parsley-maxlength="15" placeholder="Contact No.">
                                            @if ($errors->has('contact_no'))
                                                <span class="help-block form-control-feedback ">
                                                <strong>{{ $errors->first('contact_no') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col-md-6 {{ $errors->has('registration_number') ? ' has-error' : '' }}">
                                            <label for="exampleInputEmail1">Bus RegiNumber</label>
                                            <input tabindex="2" type="text" class="form-control required"
                                                   name="registration_number"
                                                   data-parsley-trigger="change" data-parsley-minlength="2"
                                                   data-parsley-maxlength="15" placeholder="Bus RegiNumber">
                                            @if ($errors->has('registration_number'))
                                                <span class="help-block form-control-feedback ">
                                                <strong>{{ $errors->first('registration_number') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label>Amenities</label>
                                            <select tabindex="-1"
                                                    class="form-control select2 js-example-basic-multiple select2-hidden-accessible"
                                                    style="width: 100%;" name="amenities[]" multiple="" id="amenities"
                                                    aria-hidden="true">

                                                @foreach($amenities as $amenity)
                                                    <option value="{{$amenity->id}}">{{$amenity->name}}</option>
                                                @endforeach
                                            </select>
                                            <span class="glyphicon  form-control-feedback"></span>
                                        </div>
                                    </div>
                                    {{csrf_field()}}
                                </div>
                            </div>
                            <div class="box-body">
                            </div>
                            <div class="col-md-12">
                                <div class="box-footer">
                                    <button tabindex="10" type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                            {{csrf_field()}}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function () {
            $(".select2").select2({
                placeholder: "-- Select --"
            });
            $('.bus_type').on('change', function () {
                $.ajax(
                    {
                        type: "GET",
                        url: "{{route('bus_type')}}",
                        data: {id: $(this).val()},
                        success: function (response) {
                            let options = [];
                            $.each(response, function (key, value) {
                                options.push({
                                    text: value.name,
                                    id: value.id
                                });
                            });

                            $('#seat-arrangement').empty().select2({data: options});
                        },
                        error: function (status) {
                            // alert(status);
                        },
                        complete: function () {
                            $('.loader').hide();
                        }
                    }
                );
            });
        });
    </script>
    <!-- /.content -->
@endsection